version: 0.2

phases:
  install:
    commands:
      - echo Installing NGINX
      - apt-get update
      - apt-get install nginx -y
  build:
    commands:
  post_build:
    commands:
      - echo Configuring NGINX

artifacts:
  files:
    - '**/*'
